providers = ["java"]

[phases.setup]
nixPkgs = ["jdk21"]

[phases.build]
cmds = [
    "chmod +x ./mvnw",
    "./mvnw -B -DskipTests clean package"
]

[start]
cmd = "java -jar target/app.jar"

[variables]
JAVA_VERSION = "21"
